### ISSUE TITLE
Re-download files

### ISSUE THREAD

**Issue by leonardosecchin** [JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl#28]
Hi,
Apparently when a fetch_ssmc is executed, the matrices already downloaded are download again.
This is critical if large matrices is included in several fetch_ssmc.
In addition, this causes unnecessary writting to the hard drive.

**Comment by dpo** [comment]
Could you show an example? It’s certainly not the intention: https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/blob/master/src/SuiteSparseMatrixCollection.jl#L75

Also, you might try #26 where we use artifacts.

**Comment by leonardosecchin** [comment]
Suppose we download 1138_bus:
fetch_ssmc("1138_bus", format="MM")
The file "~/.julia/...../data/MM/HB/1138_bus.tar.gz" will be created and deleted just after unzipping it.
This tar.gz file is created each time fetch_ssmc is run.
It is difficult to see this, however, if we read the tar.gz directory at the exact time, we can see the compressed file before it is automatically deleted.
I believe it is always decompressed. Anyway, even downloading tar.gz is unecessary.
I created a script that tests whether the mtx file exists first. It runs much faster than using fetch_ssmc on the entire list of selected matrices.

**Comment by dpo** [comment]
> Apparently it does not handle the mtx extension properly.

You'll have to either be more specific or open a pull request.

**Comment by leonardosecchin** [comment]
There are many ways to solve the problem...

After
https://github.com/JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl/blob/master/src/SuiteSparseMatrixCollection.jl#L72
add
extfile = format == "mat" ? "mat" : (format == "MM" ? "mtx" : (format == "RB" ? "rb" : "tar.gz"))

Line 74 should be
fname = format == "mat" ? joinpath(g_path, "$(matrix.name).$(extfile)") : joinpath(g_path, "$(matrix.name)/$(matrix.name).$(extfile)")
since the files mtx and rb are extracted to the directory "g_path/$(matrix.name)" (see line 80).

On lines 80 and 81, we assume that tar.gz exists. So:
Line 78 should be "else"
Line 82 should be "end; end"

**Comment by dpo** [comment]
Fixed in #26. Please use `master` until we release a new version.
