### ISSUE TITLE
Error with Julia 1.6.1

### ISSUE THREAD

**Issue by leonardosecchin** [JuliaSmoothOptimizers/SuiteSparseMatrixCollection.jl#38]
After I upgraded my Julia from 1.5.3 to the newest stable version 1.6.1, SuiteSparseMatrixCollection.jl crashed. Even installing Julia 1.6.1 and all packages from scratch, the error persists.
Output of   ]test SuiteSparseMatrixCollection  :

Testing Running tests...
┌ Info: loaded database with revision date
└   last_rev_date = "08-Oct-2020 17:09:58"
          Downloaded artifact: Pajek/Stranke94.MM
  Downloaded artifact: Pajek/Stranke94.MM
ERROR: LoadError: Unable to automatically install 'Pajek/Stranke94.MM' from '/home/leonardo/.julia/packages/SuiteSparseMatrixCollection/UVvEH/src/../Artifacts.toml'
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
   @ Pkg.Artifacts /opt/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:443
 [3] ensure_artifact_installed(name::String, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, pkg_uuid::Nothing, verbose::Bool, quiet_download::Bool, io::Base.TTY)
   @ Pkg.Artifacts /opt/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:406
 [4] ensure_artifact_installed(name::String, artifacts_toml::String)
   @ Pkg.Artifacts /opt/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:401
 [5] #fetch_ssmc#1
   @ ~/.julia/packages/SuiteSparseMatrixCollection/UVvEH/src/SuiteSparseMatrixCollection.jl:35 [inlined]
 [6] test_fetch()
   @ Main ~/.julia/packages/SuiteSparseMatrixCollection/UVvEH/test/runtests.jl:13
 [7] top-level scope
   @ ~/.julia/packages/SuiteSparseMatrixCollection/UVvEH/test/runtests.jl:49
 [8] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [9] top-level scope
   @ none:6
in expression starting at /home/leonardo/.julia/packages/SuiteSparseMatrixCollection/UVvEH/test/runtests.jl:49
ERROR: Package SuiteSparseMatrixCollection errored during testing

**Comment by dpo** [comment]
I think certain data files are corrupt and should be removed from the list of artefacts.

**Comment by amontoison** [comment]
The problem comes from `Artifacts`, they add restrictions for the file extensions with Julia 1.6.
I will work on a fix.

**Comment by dpo** [comment]
What restrictions? They all have the same `.tar.gz` extension.

**Comment by dpo** [comment]
I just upgraded to 1.6.2 and the tests pass for me. Do they still fail for you?
